#version: '4.38.0'

services:
  DB-subdomains:
    image: mariadb:latest
    container_name: DB-subdomains
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: subdomains
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  supervision-db:
    image: phpmyadmin/phpmyadmin
    container_name: supervision-db
    restart: always
    environment:
      PMA_HOST: DB-subdomains
      MYSQL_ROOT_PASSWORD: admin
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - my_network

  python-scripts:
    build: ./python-scripts
    container_name: python-scripts
    restart: always
    depends_on:
      - DB-subdomains
    volumes:
      - ./python-scripts:/app
      - /var/run/docker.sock:/var/run/docker.sock  # Montre le socket Docker au conteneur
    ports:
      - "8081:8081"
    networks:
      - my_network
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"  # Définit l'accès à l'API Docker

volumes:
  mariadb_data:

networks:
  my_network:
    driver: bridge
